import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.sql import func
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class AuditLog(Base):
    """architecture.md §5: partitioned by month from day 1. The `PARTITION BY` /
    monthly-partition DDL isn't expressible via SQLAlchemy's Table construct, so
    it's hand-written in the migration instead of autogenerated.

    Postgres requires every unique constraint on a partitioned table — including
    the primary key — to include the partition column. The spec's bare
    `id UUID PRIMARY KEY` would be rejected against `PARTITION BY RANGE
    (created_at)`, so the primary key here is composite (id, created_at). `id`
    alone stays effectively unique in practice since it's a random UUID.
    """

    __tablename__ = "audit_logs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), primary_key=True, server_default=func.now()
    )
    actor_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"))
    action: Mapped[str] = mapped_column(String(100), nullable=False)
    target_type: Mapped[str | None] = mapped_column(String(50))
    target_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    # DB column is named `metadata` per architecture.md §5 — mapped to a differently
    # named Python attribute since `metadata` is reserved on declarative models
    # (it's SQLAlchemy's own Base.metadata / MetaData registry).
    extra_data: Mapped[dict | None] = mapped_column("metadata", JSONB)
