"""initial schema

Revision ID: b162a8b750e5
Revises: 
Create Date: 2026-07-31 04:35:12.893074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b162a8b750e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_uri', sa.Text(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='offline', nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # audit_logs is partitioned by month (architecture.md §5, §11) — not expressible
    # via op.create_table, so it's hand-written here instead of autogenerated.
    # Postgres requires the partition column in every unique constraint including the
    # PK, so the PK is composite (id, created_at) rather than the spec's bare `id`
    # alone — see db/models/audit_log.py for the full rationale.
    op.execute("""
        CREATE TABLE audit_logs (
            id UUID NOT NULL DEFAULT gen_random_uuid(),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            actor_id UUID REFERENCES users(id),
            action VARCHAR(100) NOT NULL,
            target_type VARCHAR(50),
            target_id UUID,
            metadata JSONB,
            PRIMARY KEY (id, created_at)
        ) PARTITION BY RANGE (created_at);
    """)
    # One real partition to start (current month), plus a DEFAULT partition so
    # inserts never fail if a future month's partition hasn't been created yet.
    # Provisioning each new month's partition ahead of time is an ops task (e.g. a
    # scheduled job) — not automated here, out of scope for the schema itself.
    op.execute("""
        CREATE TABLE audit_logs_2026_07 PARTITION OF audit_logs
            FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
    """)
    op.execute("CREATE TABLE audit_logs_default PARTITION OF audit_logs DEFAULT;")
    op.create_table('channels',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_members',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='member', nullable=True),
    sa.Column('muted', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', 'user_id')
    )
    op.create_table('messages',
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('reply_to_id', sa.UUID(), nullable=True),
    sa.Column('forwarded_from_id', sa.UUID(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['forwarded_from_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('thumbnail_uri', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('is_compressed', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_reads',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id')
    )
    op.create_table('reactions',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('emoji', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id', 'emoji')
    )
    # ### end Alembic commands ###

    # --- FTS triggers (architecture.md §5) ---
    # messages.search_vector is the doc's worked example; users/channels follow the
    # same pattern since both have a search_vector column + GIN index and both are
    # in scope for GET /search?type=users|channels (architecture.md §6).
    op.execute("""
        CREATE FUNCTION messages_search_trigger() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector := to_tsvector('english', coalesce(NEW.content, ''));
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_messages_search BEFORE INSERT OR UPDATE
            ON messages FOR EACH ROW EXECUTE FUNCTION messages_search_trigger();
    """)
    op.execute("""
        CREATE FUNCTION users_search_trigger() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector := to_tsvector('english',
                coalesce(NEW.display_name, '') || ' ' || coalesce(NEW.email, ''));
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_users_search BEFORE INSERT OR UPDATE
            ON users FOR EACH ROW EXECUTE FUNCTION users_search_trigger();
    """)
    op.execute("""
        CREATE FUNCTION channels_search_trigger() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector := to_tsvector('english',
                coalesce(NEW.name, '') || ' ' || coalesce(NEW.topic, ''));
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_channels_search BEFORE INSERT OR UPDATE
            ON channels FOR EACH ROW EXECUTE FUNCTION channels_search_trigger();
    """)

    # --- Indexes (architecture.md §5) ---
    op.execute("CREATE INDEX idx_messages_channel_created ON messages(channel_id, created_at DESC);")
    op.execute("CREATE INDEX idx_messages_sender ON messages(sender_id);")
    op.execute("CREATE INDEX idx_channel_members_user ON channel_members(user_id);")
    op.execute(
        "CREATE INDEX idx_notifications_user_unread ON notifications(user_id) WHERE is_read = false;"
    )
    op.execute("CREATE INDEX idx_messages_search ON messages USING GIN(search_vector);")
    op.execute("CREATE INDEX idx_users_search ON users USING GIN(search_vector);")
    op.execute("CREATE INDEX idx_channels_search ON channels USING GIN(search_vector);")


def downgrade() -> None:
    # --- Indexes ---
    op.execute("DROP INDEX IF EXISTS idx_channels_search;")
    op.execute("DROP INDEX IF EXISTS idx_users_search;")
    op.execute("DROP INDEX IF EXISTS idx_messages_search;")
    op.execute("DROP INDEX IF EXISTS idx_notifications_user_unread;")
    op.execute("DROP INDEX IF EXISTS idx_channel_members_user;")
    op.execute("DROP INDEX IF EXISTS idx_messages_sender;")
    op.execute("DROP INDEX IF EXISTS idx_messages_channel_created;")

    # --- FTS triggers ---
    op.execute("DROP TRIGGER IF EXISTS trg_channels_search ON channels;")
    op.execute("DROP FUNCTION IF EXISTS channels_search_trigger();")
    op.execute("DROP TRIGGER IF EXISTS trg_users_search ON users;")
    op.execute("DROP FUNCTION IF EXISTS users_search_trigger();")
    op.execute("DROP TRIGGER IF EXISTS trg_messages_search ON messages;")
    op.execute("DROP FUNCTION IF EXISTS messages_search_trigger();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reactions')
    op.drop_table('message_reads')
    op.drop_table('attachments')
    op.drop_table('messages')
    op.drop_table('channel_members')
    op.drop_table('sessions')
    op.drop_table('notifications')
    op.drop_table('channels')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('roles')
    op.drop_table('departments')
    # ### end Alembic commands ###
